<?php
 /*
  * This file is part of evQueue
  * 
  * evQueue is free software: you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation, either version 3 of the License, or
  * (at your option) any later version.
  * 
  * evQueue is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with evQueue. If not, see <http://www.gnu.org/licenses/>.
  * 
  * Authors: Nicolas Jean, Christophe Marti 
  */

session_start();
session_destroy();

require_once 'inc/logger.php';
require_once 'lib/XSLEngine.php';

if(isset($DATABASES_CONFIG['queueing']))
{
	// Already configured
	die("evQueue has already been configured, if you want to re-configure it, please remove the content of the configuration files (but keep files in place)");
}

$xsl = new XSLEngine();

if(isset($_POST['db_host']) && isset($_POST['db_user']) && isset($_POST['db_password']) && isset($_POST['db_name']) && isset($_POST['engine_host']) && isset($_POST['engine_port']))
{
	$error = false;
	
	try
	{

		$wfi = new WorkflowInstance($_POST['engine_host'],$_POST['engine_port']);
		$wfs = $wfi->GetRunningWorkflows();
		if($wfs===false)
			throw new Exception("Unable to connect to evQueue engine");
		
	
		
		$f = @fopen("$path_to_conf/queueing.php",'w',true);
		if($f===false)
			throw new Exception("Unable to open config file '$path_to_conf/queueing.php'");
		
		fputs($f,"<?php\n// This file has been generated by install.php\n\$QUEUEING = [\n\t'localhost' => 'tcp://{$_POST['engine_host']}:{$_POST['engine_port']}'\n];\n?>");
		
		fclose($f);
		
		$site_base = dirname($_SERVER['REQUEST_URI']);
		if($site_base!="/")
			$site_base .= '/';
		$site_base = "http://{$_SERVER['HTTP_HOST']}$site_base";
		
		$f = @fopen("$path_to_conf/sites_base.php",'w',true);
		if($f===false)
			throw new Exception("Unable to open config file '$path_to_conf/sites_base.php'");
		
		fputs($f,"<?php\n// This file has been generated by install.php\ndefine('SITE_BASE','$site_base');\n?>");
		
		fclose($f);
		

		
		if (is_callable(opcache_reset))
			opcache_reset();  // this is necessary because the databases.php conf file is going to change, and opcache will keep the previous (empty) version if we don't prevent it
		
		header("Location: auth.php");
		die();
		
	}
	catch(Exception $e)
	{
		$xsl->SetParameter('ERROR',$e->getMessage());
	}
}

$xsl->DisplayXHTML('xsl/install.xsl');
?>
