<?php
 /*
  * This file is part of evQueue
  *
  * evQueue is free software: you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation, either version 3 of the License, or
  * (at your option) any later version.
  *
  * evQueue is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with evQueue. If not, see <http://www.gnu.org/licenses/>.
  *
  * Authors: Nicolas Jean, Christophe Marti
  */

session_start();
session_destroy();

if(is_file('/etc/evqueue/conf/queueing.php') || is_file(__DIR__ . '/includes/conf/queueing.php'))
{
	if(is_file('/etc/evqueue/conf/queueing.php'))
		require '/etc/evqueue/conf/queueing.php';
	else if(is_file(__DIR__ . '/includes/conf/queueing.php'))
		require __DIR__ . '/includes/conf/queueing.php';
	
	if(isset($QUEUEING) && count($QUEUEING) > 0)
		die('Configuration file already exists, install is disabled');
}

require_once __DIR__ . '/includes/inc/logger.php';
require_once __DIR__ . '/includes/lib/XSLEngine.php';
require_once __DIR__ . '/includes/lib/evQueue.php';

$xsl = new XSLEngine();

$engine_conf = false;
if(isset($_POST['type']) && $_POST['type']=='tcp' && isset($_POST['engine_host']) && isset($_POST['engine_port']))
	$engine_conf = "tcp://{$_POST['engine_host']}:{$_POST['engine_port']}";
else if(isset($_POST['type']) && $_POST['type']=='unix' && isset($_POST['engine_path']))
	$engine_conf = "unix://{$_POST['engine_path']}";


if($engine_conf!==false)
{
	$error = false;
	try
	{
		
		try{
			$evqueue = new evQueue($engine_conf);
			$evqueue->Api('ping');
		}
		catch(Exception $e){
			if($e->getCode() != evQueue::ERROR_AUTH_REQUIRED) //it's ok if engine require auth
				throw $e;
		}
		
		if(is_file('/etc/evqueue/conf/queueing.php'))
			$f = @fopen('/etc/evqueue/conf/queueing.php','w');
		else if(is_file(__DIR__ . '/includes/conf/queueing.php'))
			$f = @fopen(__DIR__ . '/includes/conf/queueing.php','w');
		else
			die("No configuration file found");
		
		if($f===false)
			throw new Exception("Unable to open config file 'conf/queueing.php'");
		
		fputs($f,"<?php\n// This file has been generated by install.php\n\$QUEUEING = [\n\t'$engine_conf'\n];\n?>");
		fclose($f);
		
		header("Location: auth.php");
		die();
	}
	catch(Exception $e)
	{
		$xsl->SetParameter('ERROR',$e->getMessage());
	}
}

$xsl->DisplayXHTML('xsl/install.xsl');
?>
