#!/bin/bash

if [ "$1" = "configure" ]; then

	if [ -d /etc/apache2/conf.d ]; then
		ln -s /etc/evqueue/apache.conf /etc/apache2/conf.d/evqueue.conf
	elif [ -d /etc/apache2/conf-available ]; then
		ln -s /etc/evqueue/apache.conf /etc/apache2/conf-available/evqueue.conf
		/usr/sbin/a2enconf evqueue
	fi
	
	if [ -x /usr/sbin/invoke-rc.d ]; then
		invoke-rc.d apache2 restart
	else
		/etc/init.d/apache2 restart
	fi
	
	if [ ! -f /etc/evqueue/conf/databases.php ]; then
		touch /etc/evqueue/conf/databases.php
	fi
	
	if [ ! -f /etc/evqueue/conf/logger.php ]; then
		touch /etc/evqueue/conf/logger.php
	fi
	
	if [ ! -f /etc/evqueue/conf/queueing.php ]; then
		touch /etc/evqueue/conf/queueing.php
	fi
	
	if [ ! -f /etc/evqueue/conf/sites_base.php ]; then
		touch /etc/evqueue/conf/sites_base.php
	fi
	
	chown -R www-data:www-data /etc/evqueue/conf
	chown -R www-data:www-data /usr/share/evqueue

fi